# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionCRUD', '0002_auto_20160404_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conn',
            name='name',
        ),
        migrations.AddField(
            model_name='conn',
            name='datasource_name',
            field=models.CharField(choices=[('chevrolet', 'Chevrolet'), ('mazda', 'Mazda'), ('nissan', 'Nissan'), ('toyota', 'Toyota'), ('mitsubishi', 'Mitsubishi')], default='mazda', max_length=200),
        ),
    ]
