# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionCRUD', '0004_auto_20160405_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conn',
            name='pages',
        ),
        migrations.AddField(
            model_name='conn',
            name='connection_type',
            field=models.CharField(choices=[('API', 'API'), ('Username Password', 'Username Password')], default='API', max_length=200),
        ),
        migrations.AlterField(
            model_name='conn',
            name='name',
            field=models.CharField(choices=[('Google Analytics', 'Google Analytics'), ('mazda', 'Mazda'), ('nissan', 'Nissan'), ('toyota', 'Toyota'), ('mitsubishi', 'Mitsubishi')], default='Google Analytics', max_length=200),
        ),
    ]
