# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionCRUD', '0006_auto_20160405_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conn',
            name='password_if_required',
            field=models.CharField(blank=True, default='Password (If Required)', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='conn',
            name='username_or_apikey',
            field=models.CharField(default='Username / API Key', max_length=600),
        ),
    ]
