# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionCRUD', '0007_auto_20160405_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conn',
            name='name',
            field=models.CharField(choices=[('Google Analytics', 'Google Analytics'), ('Mailchimp', 'Mailchimp'), ('Shopify', 'Shopify'), ('Facebook', 'Facebook'), ('SugarCRM', 'SugarCRM'), ('ExactTarget', 'ExactTarget'), ('WooCommerce', 'WooCommerce')], default='Google Analytics', max_length=200),
        ),
    ]
