# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapi', '0002_auto_20160125_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_db_model',
            name='search_value',
        ),
    ]
