# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdb',
            old_name='customer_username',
            new_name='customer_ID',
        ),
    ]
