# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmain', '0003_auto_20160329_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdatasources',
            name='data_source_type',
        ),
        migrations.DeleteModel(
            name='CustomerDataSources',
        ),
        migrations.DeleteModel(
            name='DataSources',
        ),
    ]
