# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmain', '0004_auto_20160405_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='alertbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_title', models.CharField(blank=True, max_length=600, null=True)),
                ('alert_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('alert_link', models.CharField(blank=True, max_length=600, null=True)),
                ('alert_date', models.DateTimeField(auto_now_add=True)),
                ('alert_2', models.CharField(blank=True, max_length=600, null=True)),
                ('alert_3', models.CharField(blank=True, max_length=600, null=True)),
                ('alert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='custdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=120)),
                ('cust_id', models.CharField(max_length=120)),
                ('cust_email', models.CharField(max_length=2000)),
                ('cust_table', models.CharField(max_length=200)),
                ('cust_gender', models.CharField(blank=True, max_length=600, null=True)),
                ('cust_agegroup', models.CharField(blank=True, max_length=600, null=True)),
                ('cust_address', models.CharField(blank=True, max_length=2000, null=True)),
                ('cust_state', models.CharField(blank=True, max_length=600, null=True)),
                ('cust_country', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_status', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_special', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_referredby', models.CharField(blank=True, max_length=120, null=True)),
                ('cust_referredRoot', models.CharField(blank=True, max_length=120, null=True)),
                ('cust_joindate', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_lastactive', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subchart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.CharField(blank=True, max_length=120, null=True)),
                ('chart_title', models.CharField(blank=True, max_length=600, null=True)),
                ('chart_id', models.CharField(blank=True, max_length=600, null=True)),
                ('chart_exp', models.CharField(blank=True, max_length=2000, null=True)),
                ('chart_base', models.CharField(blank=True, max_length=600, null=True)),
                ('chart_parent_id', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
