# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmain', '0005_alertbox_custdb_subchart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='custdb',
        ),
    ]
